#!/bin/sh

. "$HOME/mine/config/dotfiles/.initvars"
DOTFILESNAME="${DOTFILES#$HOME/}"
do_link() {
	orig="$1"
	dest="$2"
	borig=`basename "$orig"`
	[ "x$borig" = "x." -o "x$borig" = "x.." -o "x$borig" = "x*" -o "x$borig" = "x.*" ] && return 1
	[ -z "$dest" ] && dest="$borig"
	#echo "orig: $orig, dest: $dest"
	if [ ! -e "$orig" ]; then return 1; fi
	if [ -e "$dest" -a ! -h "$dest" ]; then
		echo "Warning: mv $dest $dest.old"
		mv "$dest" "$dest.old";
	fi
	if [ -h "$dest" ]; then
		destlink=`readlink "$dest"`
		if [ "$orig" != "$destlink" ]; then
			echo "$dest -> $orig"
			ln -snf "$orig" "$dest"
		fi
	else
		echo "$dest -> $orig"
		ln -s "$orig" "$dest"
	fi
}

cd "$HOME"
echo "# dotfiles"
for i in "$DOTFILESNAME"/{*,.*}(N); do
	case `basename "$i"` in
	dotfiles*) ;; #do nothing
		*)
			do_link "$i" ;;
	esac
done

#we only go one level down
echo "# squel"
for dir in "$DOTFILESNAME/dotfiles-squel"/{*,.*}(/N); do
	mkdir -p -m 700 "$HOME/$dir"
	cd "$HOME/$dir"
	for i in "../$DOTFILESNAME/dotfiles-squel/$dir"/{*,.*}(N); do
		do_link "$i"
	done
done

echo "# symlinks"
cd "$HOME"
do_link mine/config
mkdir -p tmp/
cd "$HOME/.ssh"
do_link authorized_keys.default authorized_keys

[ -e "$HOME/.ssh/authorized_keys" ] || echo "!! ~/.ssh/authorized keys does not exist!"
