#! /bin/sh


#PATH=/bin:/usr/bin:/usr/local/bin/:/sbin/:/usr/sbin/

start ()
{
    echo -n "Starting aMule"
    exec amule >> "$HOME/.aMule/Log-aMule" &
    echo "."
}

stop ()
{
    echo -n "Stopping aMule"
    pkill -u "$USER" amule
    echo "."
}


case "$1" in
  start)
	start
    ;;
  stop)
	stop
    ;;
  reload)
	  stop
	  start
    ;;
  force-reload|restart)
	stop
	start
	;;
  *)
    echo "Usage: /etc/init.d/$0 {start|stop|restart|force-reload|reload}"
    exit 1
    ;;
esac

exit 0
