#!/bin/zsh
#arch-chroot

for bootldr in $BOOTLOADER; do
	case $bootldr in
		grub) #bios
			grub-install --directory=/usr/lib/grub/i386-pc --target=i386-pc --boot-directory=/boot --recheck $DISK || return 1 ;;
			#modifier /etc/grub.d/40_custom pour rajouter windows
			#editer ~etc/default/grub
			#grub-mkconfig -o /boot/grub/grub.cfg
		syslinux ) #bios
			#no need for -a, I already marked the partition bootable (and -a only work for mbr partitions anyway)
			#-m: install mbr, -i: install syslinux (-u: update syslinux)
			syslinux-install_update -i -m || return 1 ;;
		gummiboot) #efi
			gummiboot install || return 1 ;;
		systemd-boot) #efi
			bootctl install || return 1 ;;
	esac
done

if [[ -n $BOOTBACKUP ]]; then
	mkdir -p /boot/linux-init
	cp /boot/{vmlinuz-linux,initramfs-linux.img,initramfs-linux-fallback.img} /boot/linux-init/
fi
