#!/bin/zsh
echo "Generate etc files"
$MYFILES/syst/etc/generate.rb
echo "Diff files? (y/n)"
read a
if [ "x$a" = "xy" ]; then
$MYFILES/syst/etc/01diffetc "$@"
fi
echo "Commit files"
$MYFILES/syst/etc/02commitetc
