#!/bin/zsh

#EFI mode
sgdisk -n 1:0:+150M -c "0:$BOOTPARTLABEL" -t '0:ef00' --attributes=1:set:2 \
  -n 2:0:+1G -c "0:$SWAPPARTLABEL" -t '0:8200' \
  -n 3:0:+2G -c "0:$SLASHPARTLABEL" -t '0:8300' \
  -n 4:0:0 -c "0:$HOMEPARTLABEL" -t '0:8302' $DISK

