default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.living_room
    - group.chambre_ami
    - group.chambre_olympe
    - group.chambre_damien
    - group.buanderie
    - group.bureau
    - group.garage
    - group.gps
    - group.outside

outside:
  name: Dehors
  icon: mdi:weather-sunset
  entities:
    - sensor.yr_symbol
    - sun.sun
living_room:
  name: Salon
  entities:
    - media_player.living_room_speaker
    - sensor.temperature_living_room
    - sensor.humidity_living_room
    - binary_sensor.motion_sensor_stairs
    - sensor.illumination_living_room
    - binary_sensor.switch_xiaomi_gateway
    - light.xiaomi_gateway_light
    - media_player.mibox
    - binary_sensor.door_window_sensor_158d000201b6c8
garage:
  name: Garage
  icon: mdi:garage
  entities:
    - binary_sensor.door_window_sensor_garage
chambre_olympe:
  name: Chambre Olympe
  icon: mdi:bed-empty
  entities:
    - sensor.temperature_olympe
    - sensor.humidity_olympe
    - sensor.pressure_olympe
    - binary_sensor.motion_sensor_olympe
    - sensor.illumination_olympe
chambre_damien:
  name: Chambre Damien
  icon: mdi:bed-empty
  entities:
    - sensor.temperature_damien
    - sensor.humidity_damien
    - sensor.pressure_damien
buanderie:
  name: Buanderie
  icon: mdi:bed-empty
  entities:
    - sensor.temperature_buanderie
    - sensor.humidity_buanderie
    - sensor.pressure_buanderie
chambre_ami:
  name: Chambre d'Ami
  icon: mdi:bed-empty
  entities:
    - sensor.temperature_ami
    - sensor.humidity_ami
    - sensor.pressure_ami
bureau:
  name: Bureau
  icon: mdi:bed-empty
  entities:
    - sensor.temperature_bureau
    - sensor.humidity_bureau
    - sensor.pressure_bureau
rooms:
  view: true
  icon: mdi:bed-empty
  name: Pièces
  entities: group.living_room, group.chambre_ami, group.chambre_olympe, group.chambre_damien, group.buanderie, group.bureau, group.garage

bluetooth:
  name: Bluetooth Tracking
  entities:
    - device_tracker.mibox
    - device_tracker.galaxy_a8_2018
    - device_tracker.ue_boom_right
    - device_tracker.ue_boom_left
    - device_tracker.tvsamsung_led48
wifi:
  name: Wifi Tracking
  entities:
    - device_tracker.149f3c4e2557
    - device_tracker.durin
    - device_tracker.20dfb94747a6
    - device_tracker.34ce00e49c83
    - device_tracker.f0b429cc11c9
gps:
  name: GPS Tracking
  entities:
    - device_tracker.5200527cb4b91553
tracking:
  name: Tracking
  icon: mdi:map-marker-radius
  view: true
  entities: group.wifi, group.gps, group.bluetooth
