# Bluetooth
mibox:
  hide_if_away: true
  icon:
  mac: BT_00:9E:C8:AF:CC:60
  name: Mibox BT
  picture:
  track: true
  vendor: Xiaomi Communications Co Ltd

galaxy_a8_2018:
  hide_if_away: true
  icon:
  mac: BT_14:9F:3C:4E:25:56
  name: Galaxy A8 (2018) BT
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

ue_boom_right:
  hide_if_away: true
  icon:
  mac: BT_88:C6:26:07:18:A6
  name: UE BOOM Right
  picture:
  track: true
  vendor: Logitech, Inc

ue_boom_left:
  hide_if_away: true
  icon:
  mac: BT_88:C6:26:06:F4:D1
  name: UE BOOM Left
  picture:
  track: true
  vendor: Logitech, Inc

tvsamsung_led48:
  hide_if_away: true
  icon:
  mac: BT_FC:F1:36:B7:44:CC
  name: '[TV]Samsung LED48 BT'
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

# GPS
5200527cb4b91553:
  hide_if_away: false
  icon:
  mac:
  name: Dam's GPS Logger
  picture:
  track: true
  vendor: Samsung A8

# Wifi
149f3c4e2557:
  hide_if_away: true
  icon:
  mac: 14:9F:3C:4E:25:57
  name: Samsung A8 Wifi
  picture:
  track: true
  vendor: unknown

durin:
  hide_if_away: true
  icon:
  mac: B8:27:EB:0A:E7:6E
  name: Durin Wifi
  picture:
  track: true
  vendor: Raspberry Pi Foundation

20dfb94747a6:
  hide_if_away: true
  icon:
  mac: 20:DF:B9:47:47:A6
  name: Home Mini Wifi
  picture:
  track: true
  vendor: unknown

34ce00e49c83:
  hide_if_away: true
  icon:
  mac: 34:CE:00:E4:9C:83
  name: Xiaomi Camera 360° Wifi
  picture:
  track: true
  vendor: XIAOMI Electronics,CO.,LTD

f0b429cc11c9:
  hide_if_away: true
  icon:
  mac: F0:B4:29:CC:11:C9
  name: Xiaomi Gateway Wifi
  picture:
  track: true
  vendor: unknown

009ec8b4603f:
  hide_if_away: false
  icon:
  mac: 00:9E:C8:B4:60:3F
  name: Mibox Wifi
  picture:
  track: true
  vendor: Xiaomi Communications Co Ltd

fcf136b63b3d:
  hide_if_away: false
  icon:
  mac: FC:F1:36:B6:3B:3D
  name: '[TV]Samsung LED48 Wifi'
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

c8387064017f:
  hide_if_away: false
  icon:
  mac: C8:38:70:64:01:7F
  name: Téléphone Blandine
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

feanor:
  hide_if_away: false
  icon:
  mac: DC:85:DE:74:F5:F5
  name: feanor
  picture:
  track: true
  vendor: AzureWave Technology Inc.

fleurbleue:
  hide_if_away: false
  icon:
  mac: 00:16:EB:C9:C0:57
  name: FleurBleue
  picture:
  track: true
