(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'direct)
(define default-im-name 'direct)
(define enabled-im-list '(latin elatin m17n-en-ispell m17n-fr-azerty m17n-rfc1345 m17n-unicode m17n-latn-pre m17n-latn-post ipa-x-sampa look anthy-utf8))
(define enable-im-switch? #f)
(define switch-im-key '("<Control>Shift_key" "<Shift>Control_key"))
(define switch-im-key? (make-key-predicate '("<Control>Shift_key" "<Shift>Control_key")))
(define switch-im-skip-direct-im? #f)
(define enable-im-toggle? #f)
(define toggle-im-key '("<IgnoreCase><Control>w"))
(define toggle-im-key? (make-key-predicate '("<IgnoreCase><Control>w")))
(define toggle-im-alt-im 'elatin)
(define uim-color 'uim-color-uim)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
