#!/bin/bash

list_package_files() {
	(find . -path './.*' \! -name '.'; find . \! -path './.*' \! -name '.' | LC_ALL=C sort) |
	sed -e 's|^\./||' | tr '\n' '\0'
}

list_package_files | LANG=C bsdtar -cnf - --format=mtree \
	--options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
	--null --files-from - --exclude .MTREE | gzip -c -f -n > .MTREE
