#!/bin/sh

. "$HOME/mine/config/dotfiles/.initvars"
export DOTFILES

if [ -e "$CFGFILES/11do-update-full" ]; then
	mylog "update" "~config/10update (type=full; $0 $@)"

	"$CFGFILES"/10update-full "$@"
else
	mylog "update" "~config/10update (type=light; $0 $@)"
	"$CFGFILES"/10update-light "$@"
fi
