vim: ft=markdownlight fdm=expr

TODO: EGA IV.13, 14, 15 sur les morphismes equidimensionnels, la dimension des fibres des morphismes univ ouverts et les références pour le cas univ caténaire

Normalisation de Noether
========================

Shape lemma
-----------

Par normalisation de Noether, on peut se ramener à S=k[x1,...,xn]/I avec I
de dim 0. Si I est radical alors on a le shape lemma. Plus de détails dans
The shape of the shape lemma:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.27.618&rep=rep1&type=pdf

Voir aussi les bases triangulaires d'idéaux:
https://www.sciencedirect.com/science/article/pii/S0747717108800867?via%3Dihub
Solving zero-dimensional algebraic systems, D.Lazard, 1992.

Cas d'un corps
--------------

* https://stacks.math.columbia.edu/tag/00OY
$ 10.114 Noether normalization
Lemma 10.114.4. Let k be a field. Let S=k[x1,…,xn]/I for some ideal I. If I≠(1), there exist r≥0, and y1,…,yr∈k[x1,…,xn] such that (a) the map k[y1,…,yr]→S is injective, and (b) the map k[y1,…,yr]→S is finite. In this case the integer r is the dimension of S.
Moreover we may choose yi to be in the Z-subalgebra of k[x1,…,xn] generated by x1,…,xn.

On peut controler plus finement (cf la version d'Eisenbud pour encore plus
e controle):
Lemma 10.114.6. Let k be a field. Let q⊂k[x1,…,xn] be a prime ideal. Set r=trdegk κ(q). Then there exists a finite ring map φ:k[y1,…,yn]→k[x1,…,xn] such that φ−1(q)=(yr+1,…,yn).

$ https://en.wikipedia.org/wiki/Noether_normalization_lemma
Version d'Eisenbud:

Theorem — Let A be a finitely generated algebra over a field k, and I1 ⊂ ⋯ ⊂ Im be a chain of ideals such that dim(A/Ii) = di > di + 1. Then there exists algebraically independent elements y1, ..., yd in A such that
  - A is a finitely generated module over the polynomial subring S = k[y1, ..., yd].
  - Ii ∩ S = (y_di+1 , … , y_d )
  - If the Ii  are homogeneous, then yi's may be taken to be homogeneous.
Moreover, if k is an infinite field, then any sufficiently general choice of yi's has Property 1 above ("sufficiently general" is made precise in the proof).

Cas des anneaux intègres
------------------------

Lemma 10.114.7. Let R→S be an injective finite type ring map. Assume R is a domain. Then there exists an integer d and a factorization R→R[y1,…,yd]→S′→S 
by injective maps such that S′ is finite over R[y1,…,yd] and such that S′_f≅S_f for some nonzero f∈R.

Voir aussi http://www.math.lsa.umich.edu/~hochster/615W10/supNoeth.pdf Noether normalization theorem.
Ou https://ia803001.us.archive.org/31/items/Keerthi_Madapusi___Commutative_Algebra/CA.pdf Corollary 8.1.3

Mais la preuve de stack est plus précise: quitte à localiser (sur R) on a
Spec S fini sur A^n_R, mais on a même sans localiser des morphismes
dominants Spec S-> Spec S' - fini -> sur A^n_R avec Spec S_f=Spec S'_f pour
f dans R.

Preuve: S est engendré par les yi sur R. On prend une normalisation de Noether pour S \tens K(R), ie il est fini sur K(R)[xi], et on peut supposer les xi dans S (on n'a même pas besoin de les multiplier par un élément de R car la preuve de Noether montre que les xi sont une Z-combinaison de yi, donc sont dans S).
Ainsi yi est entier sur K(R)[xi], et en prenant f donné par le produit des dénominateurs des coefficients des pol annulateurs (quitte à prendre encore un ouvert si on ne suppose pas S intègre) on voit que yi est entier sur R_f[xi], donc S_f fini sur R_f[xi] (avec les mêmes polynômes annulateurs pour les y_i). Mais en fait on peut aussi remplacer y_i par fy_i, S'=R[xi, gy_i] est donc fini sur R, et S'_f=S_f.

Autrement dit on peut remplacer S par S' avec Spec S -> Spec S' birationnel
dominant et Spec S' qui est fini sur A^n_R, et sur R_g, S_g=S'_g et on a les
mêmes générateurs et relations que sur K(R). Et quitte à remplacer S par un
ouvert, on peut supposer que ces générateurs sont ceux de K(S).
On a même plus fort, dans le cas d'un morphisme dominant génériquement fini
X -> Spec R de schémas intègres. On prend donc un ouvert affine Spec S de
X, et on a donc vu qu'en remplaçant R par R_g, on a Spec S - fini -> A^n_R
-> R. Ici n=0, donc Spec S est donc propre sur R, donc fermé
dans X, donc X=Spec S! On retrouve qu'un morphisme quasi fini en le point
générique est fini au dessus d'un ouvert de la base.

Généralisations
---------------

* https://stacks.math.columbia.edu/tag/00QE (ou EGA IV.13.3.1.1, ega4c)
$ 10.124 Dimension of fibres

Lemma 10.124.2 Let R→S be a finite type ring map. Let q⊂S be a prime.
Suppose that dim_q(S/R)=n (dim_q(S/R) est la dimension de la fibre
contenant q). There exists a g∈S, g∉q such that S_g is quasi-finite over a
polynomial algebra R[t1,…,tn]. 
Preuve: utilise le ZMT. Par Noether la fibre est finie sur κ(p)[t1…,tn],
donc S est quasi-finie en q, donc quasi finie sur un ouvert autour de q.

En utilisant 10.114.6 on peut controler plus finement:
Lemma 10.124.3: De plus, si on note tr deg_κ(p) κ(q)=r où q->p sur R, alors
on peut écrire R_f[x1,…,xn]⟶S_g quasi fini (où f∉p, g∉q) tel que
φ−1(q S_g)=(p,xr+1,…,xn)R_f[xr+1,…,xn]

Note importante:
Si de plus f est équidimensionel en x de dim n, alors le morphisme
quasi-fini U->Y[T1,...,Tn] déduit est dominant (et réciproquement),
ie l'image d'une composante irréductible de U est dense dans une composante
irréductible de Y[T1...Tn]. Cf EGA IV.13.3.1

* https://stacks.math.columbia.edu/tag/0CBG
$ 32.18 Variants of Noether normalization

Lemma 32.18.1. Let f:X→S be a morphism of schemes. Let x∈X with image s∈S. Let V⊂S be an affine open neighbourhood of s. If f is locally of finite type and dim_x (Xs)=d, then there exists an affine open U⊂X with x∈U and f(U)⊂V and a factorization U→π A^d_V→V of f|U:U→V such that π is quasi-finite.
Preuve: Reformulation de 10.124.2

Lemma 32.18.2. Let f:X→S be a finite type morphism of affine schemes. Let s∈S. If dim(Xs)=d, then there exists a factorization X→π A^d_S→S
of f such that the morphism π_s:X_s→A^d_κ(s) of fibres over s is finite.

Lemma 32.18.3. Si f unramified/étale at x, on peut prendre U -j-> Spec(A[t]_g′/(g))->Spec(A[t])=A^1_V -> V tel que j est une immersion (resp. immersion ouverte). Cf [#étale] plus bas.

Lemma 32.18.4. Let f:X→S be a finite type morphism of affine schemes. Let x∈X with image s∈S. Let r=dim_κ(x) Ω_X/S,x ⊗_OX,x κ(x)=dim_κ(x) Ω_Xs/s,x ⊗O_Xs,x κ(x)=dim_κ(x) T_{X/S,x}
Then there exists a factorization X→π A^r_S→S of f such that π is unramified at x.

Lemma 32.18.5. Et donc en appliquant la décomposition précédente, on voit
que si f est loc. de type fini, on peut décomposer autour de x:
U →j D →j′ A^{r+1}_V →p A^r_V → V où j et j' sont des immersions et poj'
est standard étale; autrement dit on peut décomposer en
U→A^{r+1}_V→V où la première flêche est une immersion, ou en
U→D→V où la première flêche est une immersion fermée et la deuxième lisse
de dimension relative r.

Interprétation géométrique
--------------------------

* https://mathoverflow.net/questions/42276/noethers-normalization-lemma-over-a-ring-a

- The geometric interpretation of Noether's normalization lemma is that any
  affine algebraic variety has a finite surjective morphism to the affine
  space A^d_k of dimension d=dim X. 

- When k is an integral domain, and X dominates Spec(k), the finite
  surjective morphism of the generic fiber of X to A^d_K, where K=Frac(k)
  extends to a finite surjective morphism X_V→A^d_V for some dense open
  subset V of Spec(k). This is the geometric interpretation of the
  statement in M. Hochster's note in Harry Gindi's post.
  http://www.math.lsa.umich.edu/~hochster/615W10/supNoeth.pdf
  [Noether normalization theorem. Let D be an integral domain and let R be any finitely generated D-algebra extension of D.  Then there is a nonzero element c∈D and elements z1, ... ,zd in Rc algebraically  independent  over Dc such  that Rc is  module-finite  over  its subring Dc[z1, ... ,zd], which is isomorphic to a polynomial ring (d may be zero) over Dc.In particular, if D=K, a field, then it is not necessary to invert an element:  every finitely generatedK-algebra is isomorphic with a module-finite extension of a polynomial ring!]

- In general, such a morphism can not exist because it would imply that the
  fibers of X→Spec(k) all have the same dimension.
  Suppose that this condition is satisfied: the fibers of X→Spec(k) all
  have the same dimension d. Then I think that a reasonable statement
  (Noether's normalization lemma over a ring k) would be: there exists a
  quasi-finite and surjective morphism X→A^d_k. If k is noetherian, then by
  Zariski's Main Theorem, this implies that X is an open subscheme of
  a scheme which is finite surjective over A^d_k. In general one can not expect
  better result than quasi-finite (consider the case d=0).
  The above "reasonable statement" should be easy to prove when k is a
  local ring. 

  Note: EGA IV.13.3.1 montre que c'est vrai quitte à localiser X autour de x
  (x étant équidimensionnel), en remplaçant 'surjectif' par 'dominant'

- Contre exemple à la forme forte:
  https://www.ams.org/journals/proc/2007-135-11/S0002-9939-07-09010-7/S0002-9939-07-09010-7.pdf
  False Claim 1.1. Let A=R[x1,...,xn] be an integral domain, finitely generated overan infinite domain R, and let d be the transcendence degree of the field of quotients of A over the field of quotients k of R.  Then there exist d linear combinations y1,...,yd of the xi with coefficients in R, such that A is integral over R[y1,...,yd].
  This generalized lemma would be true if R were an infinite field.

Anneaux
=======

Systèmes de paramètres
----------------------

Si I=(x_1,...,x_m) alors codim I <=m (et même si P minimal sur I, codim P<=m);
réciproquement, si P premier de codim m, alors il existe x_1,...,x_m tel
que P soit minimal sur I=(x_1,...,x_m)

Séquences régulières
--------------------
{x_1,...,x_m} \subset I idéal strict de R est régulière si
x_i est non diviseur de zéro sur R/(x_1,...,x_{i-1})

depth(I)=longueur d'une (=de toutes) séquence régulière maximale

Prop: Si R local et depth I=(x_1,...,x_m)=m, alors x_1,...,x_m est
régulière.

Th: depth(I)<=codim(I)
    (et même <= tout chaine maximale qui va d'un premier minimal au dessus
    de I à un idéal associé)
Cor: si depth I=(x_1,...,x_m)=m, alors codim I=m

Si (R,m) local, {x_1,...,x_n} \subset m, alors
dim R/(x_1,...,x_n)>=dim R - n
Si x_i régulière, il y a égalité.

Déf: (R,m) régulier si dim R = dim m/m^2.

Prop: (R,m) régulier => R intégral, et donc si R de dim d et (x1,...,xd)
générateurs de m, les x_i forment une séquence régulière.

Corollaire: (R,m) régulier ssi depth(m)=dim R = codim m; et dans ce cas toute
base de m/m^2 est une séquence régulière de longueur dim R.

Intersection complète
---------------------

S est intersection complète si S=R/I où R est régulier et I engendré par
une séquence régulière. S est alors Cohen-Macauley.

Prop: Si S est intersection complète, alors pour toute surjection R->>S avec R
régulier, le noyau I est engendré par une séquence régulière.

Ex:
- les variétés lisses sont localement intersection complètes
(car localement ce sont des anneaux réguliers; si on les plonge dans un
espace vectoriel affine, l'idéal de définition est localement engendré par
un suite régulière par ce qui précède)

Si I=(x_1,...,x_n) alors depth I<=codim I<=n.
Si R est Cohen-Macauley, alors depth I=codim I et s'il
y a égalité codim I=n, alors x_1,...,x_n est régulière.

Ex: Si S est factoriel, idéal de codimension 1=idéal principal, donc
toutes les hypersurfaces sont engendrées par un élément.

Dimensions
----------

Th de la fibre: (R,m)->(S,n) morphisme local
dim S<=dim S/mS+ dim R; avec égalité si going down (ex: S/R plat)

Rem: On a toujours codim_S mS <= codim_R m (regarder les systèmes de
paramètres), ce qui donne l'interprétation géométrique ci-après pour les
variétés. *Attention*: codim_S mS n'est pas égal à dim S_m!

Th d'altitude de Nagata:
R \subset T anneau intègres, T/R de type fini.
Alors dim T_p <= dim R_p + dim fibre générique.
Si R univ caténaire et p est dans l'image de Spec T, on a égalité, et même
pour tout Q maximal dans la préimage de p:
dim T_Q=dim R_p + dim fibre générique

Si Q premier dans T au-dessus de p, on a toujours
dim T_Q+dim T_P/QT_P <= dim R_p + dim fibre générique
(car le terme de gauche est <= dim T_P).
Mais si R est univ caténaire, on a égalité.

Rem: dim fibre générique=deg tr_R(T)
     dim T_P/QT_P = deg tr_{R/P}(T/Q)

Passage à un idéal max:
----------------------

Si Q \subset R est un premier minimal et les idéaux maximaux sont denses,
alors par prime avoidance il existe P dans R maximal tel que le seul idéal
minimal de R_P soit Q_P.

Interprétation géométrique
--------------------------

Soit f:Y->X un morphisme de schémas, W \subset X irréductible, Z une
composante irréductible de f^-1(W) dominant W.
Alors dim Z >= dim W + dim fibre générique (=dim Y-dim X)
            (= si f(Z) rencontre un certain ouvert, par platitude générique)

Joujou avec les fibres
----------------------
(cf plus bas où ce passage est mieux expliqué)

S/R de types finis, R univ caténaire, Sp/pSp non vide.

1) Q idéal max de Sp/pSp, on a (th de la fibre):
dim S_Q/pS_Q >= dim S_Q - dim R_p (= si plat)

Or dim S_Q-dim R_p= dim fibre générique (th d'altitude)
Donc dim S_Q/p S_Q>= dim fibre générique (= si plat)
(rem: ça se voit aussi via la semi continuité supérieure de dim f^-1 o f)

Si de plus les points fermés sont denses, Q_0 premier minimal de S_p/pS_p,
par la prop précédente il existe Q max, dim S_p/Q_0 S_p = dim S_Q/pS_Q
Donc dim S_p/Q_0 S_p >= dim fibre générique (= si plat, on retrouve que
toutes les composantes des fibres sont de dim la dim générique pour un
morphisme plat)

2) de plus, dans l'extension R/pR - S/Q_0 S, on a
dim S/Q_0 S = dim R/pR+ dim fibre générique de cette extension (pour une variété
ou une ext CM)
     = dim S_p/Q_0S_p + dim R/pR
D'où dim S/Q_0 S = dim R/pR + dim S_p/Q_0 S_p
                 >= dimfibre générique + dim R/pR (= si plat)

3) dim S/pS c'est le max des dim des composantes de f^-1(pbar)=Q_0 \union
... Q_i
dim S_p/pS_p c'est le max des composantes de f^-1(p), ie c'est le max des
dimensions des fibres génériques des composantes précédentes

Si R et S sont des variétés, dim S/Q_i=dim R/pR + dim fibre générique en
Q_i (=dim S_p/Q_i Sp)
Donc  dim S/pS=dim S_p/pS_p + dim R/pR

Rappel: si f:Y->X, la fonction n(y)=dim f^-1(f(y)) est semi-cont
supérieurement.
ie: y/n(y)>=d est fermé
ie: si q se spécialise en p, n(p)>=n(q)

Examples
--------

1) Projection de l'hyperbole: la fibre gén est de dim 0, mais la fibre en 0
   est vide (le th de dim ne s'applique que si la fibre est non vide).
   C'est plat.

2) (x,y)->(xy,y). Dim fibre générique: 0, mais en (0,0) on a une droite:
   saut de dimension. Ce n'est pas plat.

3) Un exemple ou le going down fails:
soit X un plan que l'on replie sur lui même entre deux droites A et B.
Soit W une courbe dans X, qui intersecte A en Z0 et B en Z'0.
Soit Z le point Z'0 mis sur A, et Z' le point Z0 mis sur B.
Alors f^-1(f(W)) a pour composantes W, Z et Z' (dim 1, 0, 0)
Aucune composante contenant Z ne s'envoit dans f(W) de manière dense, donc
pas de going down, donc ce n'est pas plat (ce qui se voit aussi car les
composantes ne sont pas équidimensionnelles)

4) Si je combine 2) et 3), en repliant la droite verticale passant par 1 sur (0,0), on a que f^-1(0,0)=Oy \union 1.
Les composantes irréd sont de dim != 1.


5) Si P est un idéal premier (pas forcément maximal) dans un anneau local R,
et R->S est locale, alors si R est régulier on a codim PS <= codim P, mais
ce n'est plus vrai dans le cas général. Ex (Exo 10.6 - Eisenbud):
R=k[x,y,z,t]/(xs-yt), S=R/(x,y), P=(s,t) \subset R.
codim P = 1 mais codim PS=2.
(two planes in 4-space meeting in a point lie on the cone over a quadric
surface)

Variétés
========

Systèmes de paramètres
----------------------
Si Y est une composante irréductible de Var(f_1,...,f_r), alors codim Y<=r.

Inversement, si X est une variété affine, et codim Y=r, alors il existe
- Une chaine Y=Y_r \subset ... \subset Y_1 avec codim Y_i=i
- (f_1,...,f_r) tel que Y_i est une composante irréd de Var(f_1,...,f_i),
  et toutes les composantes irréd sont de codim i
Pr: cf www.nd.edu/~sevens/fibdim.pdf

Normalité
---------

Si f:X->Y est fini, Y normal, W \subset Y fermé, alors pour toute
composante Z de f^-1(W), f(Z)=W et dim(Z)=dim(W)
[Pr: dans ce cas on a le going down]

Prop: - Si X est une variété normale, X*k^n est normale, X_a est normale.
- Si X est une variété affine, il existe un localisé X_f normal.

Th: Soit f:X->Y un morphisme dominant de variétés, r=dim X-dim Y.
Il existe un ouvert normal V de Y tel que si U=f^-1(Y), alors il existe un
morphisme de U dans k^r tel que U->V*k^r soit fini et dominant (donc
surjectif).
[Pr: cf www.nd.edu/~sevens/fibdim.pdf, c'est un cas particulier de la
normalisation de Noether]

Dimension des fibres
--------------------

(Hartshorne exo 3.22 et 3.20)
cf aussi http://math.stanford.edu/~conrad/145Page/handouts/fiberdim.pdf

Soit f: X->Y un morphisme dominant de variétés (=schémas intègres de type
finis) sur un corps k.
Soit V \subset Y un fermé irréductible contenu dans l'adhérence de f(X) (ie
son point générique v appartient à f(X)), et U une composante irréductible de
f^-1(V) qui domine V (ie v \in f(U)). Alors
- codim(U,X) <= codim(V,Y)
- si e=dim X-dim Y = dim fibre générique
  dim(U)>=e+dim V
  En particulier, pour tout y \in f(X), les composantes irréd de la fibre
  X_y sont de dim >=e.
- par platitude générique, il existe un ouvert U de X tel que pour tout y
  fermé \in f(U), dim U_y=e.
- Pour tout n, soit E_n l'ensemble des points x \in X tels que X_f(x) a une
  composante irréductible contenant x de dim >=n.
  Alors les E_n sont fermés, E_e=X, E_n n'est pas dense si n>e.
  ie: la dimension des fibres est semi-continue sup à la source
- Pour tout n, soit D_n les points y\in Y tels que X_y soit de dim n. Alors
  les D_n sont constructibles et D_e contient un ouvert dense de Y.
  ie: si f est fermée, la dimension des fibres est semi-continue sup à la
  cible

Rappels: si X est une variété sur k, on a
(i) dim X=dim O_P pour tout P fermé
(ii) dim X=tr deg k(X)/k
(iii) Si Y fermé dans X, codim(Y,X)=inf {dim O_P,X, P \in Y}
(iv) Si Y fermé dans X, dim Y+codim(Y,X)=dim X
(v) Si U ouvert non vide de X, dim U= dim X
(vi) Si k'/k extension, les composantes irréd de X*k' sont de dim dim X.

Rem: Soit R un anneau de valuation discrète contenant son corps résiduel k.
Alors Spec R[t] ne vérifie pas (i), (iv) et (v).

Schémas
=======

Dimension des fibres
--------------------

* https://stacks.math.columbia.edu/tag/02FW
$ 29.27 Morphisms and dimensions of fibres

! Fibres
Soit f:X->Y un morphisme de schéma loc de type fini. y=f(x)

- dim_x X_y = dim O_Xy,x + trdeg_k(y) k(x)
  [Pr: dim+codim = dim globale sur une variété, or la fibre ici est de type fini sur k(y)]
  En particulier, si X et Y intègres de f dominant, dim X_ηY=trdeg_k(Y) k(X)

- dim_x(X_s)≤dim_x(X_y)+dim_y(Y_s) [X->Y->S loc. de type fini]
  Moreover, equality holds if OXs,x is flat over OYs,y, which holds for example if OX,x is flat over OY,y.
  On a aussi codim_x X <= codim_Y y  + codim_Xy x, avec égalité si f plat,
  cf FOAG plus bas.

  [Note: réciproquement, si f:X->S est un morphisme dont toutes les fibres
  ont la même dimension, avec S régulier et X Cohen-Macaulay, alors f est
  automatiquement plat, cf (EGA IV.6.1.5)
  ou https://mathoverflow.net/questions/7432/generalizing-miracle-flatness-matsumura-23-1-via-finite-tor-dimension
    Let (A,mA) and (B,mB) be noetherian local rings and f:A→B a local homomorphism. Let F=B/mAB be the fiber ring and assume that dim(B)=dim(A)+dim(F).
  ou https://mathoverflow.net/questions/75317/flatness-in-complex-analytic-geometry
  En particulier, un morphisme de variétés lisses dont les fibres sont lisses
  de la bonne dimension est plat, donc lisse]

- Si x se spécialise en x' (qui reste au dessus de y), alors
  . dim_x (X_y) <= dim_x' (X_y)
  . trdeg_k(y) k(x) > trdeg_k(y) k(x')
  . dim O_Xy,x < dim O_Xy,x'

! Pullback: (f loc. de type fini)
  - dim_x(X_s)=dim_x′(X′_s′),
  - if F is the fibre of the morphism X′_s′→X_s over x, then
    dim(OF,x′)=dim(OX′s′,x′)−dim(OXs,x)=trdeg_κ(s)(κ(x))−trdeg_κ(s′)(κ(x′))
    In particular dim(OX′_s′,x′)≥dim(OX_s,x) and trdeg_κ(s)(κ(x))≥trdeg_κ(s′)(κ(x′)).
  - given s′,s,x there exists a choice of x′ such that dim(OX′_s′,x′)=dim(OX_s,x) and trdeg_κ(s)(κ(x))=trdeg_κ(s′)(κ(x′)).

* Theorems (cf FOAG, Chapitre 11.4)

Soit f: X->Y un morphisme de prés finie de schémas, y=f(x).
- 11.4.A: codim_X x <= codim_Y y  + codim_fibre(y) x
  Si f a le going-down (ex: plat) il y a égalité.
  [Pr: utiliser les systèmes de paramètres, l'égalité est 24.5.6]
- 11.4.1. Si X et Y intègres,
  il existe un ouvert U de Y tel que les fibres en U sont
  soit vide, soit équidimensionelles de pure dimension dim X-dim Y.

[Pr: Cf la version 11.4.5:
On peut supposer f dominant (sinon il y a un ouvert ou toutes les fibres
sont vides), et on fait de la normalisation de Noether sur
fibre générique -> η_Y, que l'on étend localement à Y.
On utilise que la dimension of the generic fiber of the morphism π : X → Y
of irreducible schemes is dim X − dim Y via 11.4.A, la version plate. (ça marche ça??)
Sinon on dit que dim fibre générique = tr deg_K(Y) K(X).
Ou encore on peut appliquer le théorème de structure des morphismes de type
finis.

Note: f de prés fini est localement le pull back d'un morphisme de type
finis entre Z-anneaux de types finis, le pullback préserve les dimensions,
donc on peut toujours se ramèner au cas loc noeth de type fini sur un
anneau excellent pour étudier les dimensions.]

### Formule de la dimension (Th d'altitude de Nagata)

* https://stacks.math.columbia.edu/tag/02JT
$ 29.50 The dimension formula

- Si f loc. de type fini, Y loc. noeth,  f dominant, X et Y intègres:
  dim O_X,x <= dim O_Y,y + tr deg_K(Y) K(X) - tr deg_k(y) k(x)
  Il y a égalité si Y est universellement caténaire

  En particulier, dim(X)<=dim(Y)+dim fibre générique, avec égalité si f fermée.
  Note: dim fibre générique = tr deg_K(Y) K(X) vu que f:X->Y est dominant

- La section étend ces formules aux cas non intègres, en regardant les
  composantes irréds X_i et leur structure réduite (ce qui ne change pas la
  dim).

=> on a une dimension function:
Lemma 29.50.3. Let S be a locally Noetherian and universally catenary
scheme. Let δ:S→Z be a dimension function. Let f:X→S be a morphism of
schemes. Assume f locally of finite type. Then the map
  δ=δX/S:X⟶Z, x⟼δ(f(x))+trdeg_κ(f(x))κ(x)
is a dimension function on X, ie for every immediate specialization x⇝y in
X we have δ(x)=δ(y)+1.

* https://mathoverflow.net/questions/5982/intuition-for-nagatas-altitude-formula

Spec B -> Spec A, P -> p
ht(P)≤ht(p)+tr.d._A B−tr.d._K(p) K(P)

Put dim B=n for the dimension of the variety with coordinates ring B. Then
n-ht P ≥ ((n-tr deg A B)- ht p)+ tr deg k(p) k(P)
Si on suppose que A et B sont des variétés, alors
- The first member of the inequality indicates the dimension of the subvariety definited by P.
- The term (n-tr deg A B) in the second member is the dimension of the variety with coordinates ring A: it looses tr deg A B dimensions with respect the other variety with coordinate ring B.
- Then ((n-tr deg A B)- ht p) represent the dimension of the subvariety definited by p.
- The term tr deg k(p) k(P) is a corrector term because blow up can occur.

### Eisenbud: theorème d'altitude de Nagata et platitude des fibres spéciales

Soit f:X->Y un morphisme dominant de schéma intègres loc de type fini loc noeth. y=f(x)

- Nagata:
  dim OX_x <= dim OY_y + dim fibre générique.
  Si Y universellement caténaire et x maximal dans la fibre, il y a égalité.
  * En particulier, dim OX_y <= dim OY_y + dim fibre générique si X_y est non vide
    Si Y universellement caténaire, il y a égalité.
  * En particulier, dim X <= dim Y + dim fibre générique.
    Si les points fermés de Y sont denses et Y Cohen-Macauley (ex: Y
    variété), alors dim X=dim Y + dim fibre générique
    [Pr: car il existe un point max de Y avec une préimage non vide]

- Fibres spéciales:
  dim OX_x <= dim OY_y + dim fibre spéciale (=dim OX_x/yOX_x=dim Ofibre(y)_x)
  (ie codim_X x <= codim_Y y  + codim_fibre(y) x)
  Si X->Y est plat, il y a égalité.
  (Rem: si x est maximal dans la fibre, alors par semi continuité
  supérieure on a toujours que dim fibre spéciale = dim de la composante en x
  de la fibre en y >= dim fibre générique.
  Si X/Y plat, on retrouve que les composantes des
  fibres sont toutes de dimension=dim fibre générique (=dim X-dim Y si X,Y
  variétés))

Cor:
- dim Var(x)<=dim Var(y)+dim Var(x dans la fibre en y) (=dim OX_y/xOX_y)
  [Pr: Appliquer le Th à Var(x)->Var(y)]
  Si Y Cohen-Macauley+points fermés dense il y a égalité.
  Dans ce cas, en raisonnant sur les composantes de la fibre, on a aussi
  dim Adhérence fibre =dim Var(y)+dim fibre
  (ie dim OX/yOX = dim OY/yOY + dim OX_y/y OX_y)
- Dans le cas de variétés, dim OX_x=dim X-dim Var(x).
  D'où via dim OX_x <= dim OY_y + dim Ofibre(y)_x on tire
  dim Var(x)>=dim X-dim Y+dim Var(y)-codim de x dans la fibre
            >=dim Var(y) + dim fibre générique - codim de x dans la fibre en y
            (= si plat)

### Autres résulats:
* https://stacks.math.columbia.edu/tag/02NI
$ 29.28 Morphisms of given relative dimension

Lemma 29.28.5. Let f:X→S be a morphism of schemes. Assume f is locally of finite type. Let x∈X with s=f(x). Then f is quasi-finite at x if and only if dimx(Xs)=0. In particular, f is locally quasi-finite if and only if f has relative dimension 0.

Lemma 29.28.6. Let f:X→Y be a morphism of locally Noetherian schemes which is flat, locally of finite type and of relative dimension d. For every point x in X with image y in Y we have dim_x(X)=dim_y(Y)+d.

* https://stacks.math.columbia.edu/tag/0B2H
$ 33.19 Dimension of fibres

Lemma 33.19.2. Let f:X→Spec(R) be a morphism from an irreducible scheme to the spectrum of a valuation ring. If f is locally of finite type and surjective, then the special fibre is equidimensional of dimension equal to the dimension of the generic fibre.

Lemma 33.19.3. Let f:X→Y be locally of finite type. Let x∈X be a point with image y∈Y such that OY,y is Noetherian. Let d≥0 be an integer such that for every generic point η of an irreducible component of X which contains x, we have f(η)≠y and dim_η(X_f(η))=d. Then dim_x(X_y)≤d+dim(O_Y,y)−1.

Fiber dimension is upper semi-continuous
----------------------------------------

* Semi continuité supérieure de n: X->Z en x = il y a un voisinage U de x tel
que n(y) <= n(x) pour y dans U. En particulier si y->x, n(y) <= n(x).

Résumé: (f loc. de type fini)
+ semi-continuité supérieure à la source (f loc. de type fini)
+ en la cible, pour tout y, n_X/Y est constant sur un ouvert V de ybar.
+ Si f est plat de prés finie, n_X/Y est semi continue inférieurement
+ Si f est propre, n_X/Y est semi continue supérieurement
=> Si f plat propre de prés finie, n_X/Y est loc. constant

! Semi continuité supérieure à la source:
* https://stacks.math.columbia.edu/tag/02FW
Lemma 29.27.4. Let f:X→S be a morphism of schemes. Let n≥0. Assume f is locally of finite type. The set Un={x∈X∣dim_x X_f(x)≤n} is open in X.

! Semi continuité à la base:
* https://stacks.math.columbia.edu/tag/05F6
$ 36.28 Dimension of fibres [semi continuité]

Lemma 36.28.2. Let f:X→Y be a morphism of finite type. Let
  n_X/Y:Y→{0,1,2,3,…,∞}
be the function which associates to y∈Y the dimension of Xy. If g:Y′→Y is a morphism then n_X′/Y′=n_X/Y∘g where X′→Y′ is the base change of f.

Lemmes:
- Si f de prés finie, E_m=n_X/Y^{-1}(m) est loc. constructible
- Si y est un point générique de Y, et X_y de dimension n, alors il existe
  un ouvert V de Y tel que les fibres soient de dim n.
+ Si f est plat de prés finie, n_X/Y est semi continue inférieurement
+ Si f est propre, n_X/Y est semi continue supérieurement

[Autres références:
* https://mathoverflow.net/questions/193/when-is-fiber-dimension-upper-semi-continuous
Th (EGA IV 13.1.3): : Let f: X→Y be a morphism of schemes, locally of finite type. Then x↦dim_x(X_f(x)) is upper semi-continuous.

Corollary (Chevalley's upper semi-continuous theorem, EGA IV 13.1.5): Let
f:X→Y be proper, then: y↦dim(X_y) is upper semi-continuous.

* https://mathoverflow.net/questions/204437/why-are-unramified-maps-not-required-to-be-locally-of-finite-presentation/206333#206333
Chevalley's upper semicontinuity of fiber dimension holds for any universally closed, separated and quasi-compact morphism
]

$ Semi continuité du degré des fibres d'un morphisme fini.

- Si f est fini (surjectif), le degré des fibres est aussi semi-continu
  supérieurement.
  Et par platitude générique, il y a un ouvert où c'est le degré de [k(X):k(Y)]
  (si X, Y intègres).
  [Preuve: c'est simplement le rang du module f_* O_X sur Y.
  et on applique la semi continuité du rang d'un faisceau.
  cf aussi https://mathoverflow.net/questions/76102/upper-semicontinuity-of-multiplicities-for-finite-morphisms-between-varieties pour une réf.]

- Si de plus Y est normal (X, Y intègres), le *cardinal* de f^{-1}(y) est
  au plus [k(X):k(Y)]_s
  Dans tous les cas, il existe toujours un ouvert de Y tel qu'on ait égalité.

  [Preuve: Par 'composantes connexes des fibres' plus bas,
  si f est quasi finie dominante sur Y loc.
  noeth. unibranche, alors f est univ open et n_X/Y est semi continue
  inférieurement; donc si X intégère le cardinal géom des fibres est
  inférieur à celui de la fibré générique, qui est [k(X):k(Y)]_s.
  Voir aussi [Zariski_Main_Theorem#Lien avec la normalisation]]

* Autres exemples de semi continuité, cf FOAG 11.4.4:
(i) fiber dimension (Theorem 11.4.2 above)
(ii) the rank of a matrix of functions (because rank drops on closed subsets,
where various discriminants vanish)
(iii) the rank of a finite type quasicoherent sheaf (Exercise 13.7.J)
(iv) degree of a finite morphism, as a function of the target (§13.7.5)
(v) dimension of tangent space at closed points of a variety over an alge-
braically closed field (Exercise 21.2.J)
(vi) rank of cohomology groups of coherent sheaves, in proper flat families
(Theorem 28.1.1)
All but (ii) are upper semicontinuous; (ii) is a lower semicontinuous function.

## Rang des (groupes de cohomologies) des faisceaux

* https://math.stackexchange.com/questions/1597880/can-the-theorem-on-semicontinuity-of-fiber-dimension-be-explained-as-a-semi-cont
  If F is a finite type quasi-coherent sheaf on a scheme X, then rank(F)(p)=dim_k(p) F_p ⊗_Op k(p) is a upper semicontinuous function on X.

  Rappel: si la base est réduite, le rang est loc. constant ssi F est plat.

! Semi continuité supérieure du rang des groupes de cohomologies pour un morphisme propre et plat
* https://stacks.math.columbia.edu/tag/0BDN
$ 36.29 Application

Lemma 36.29.1. Let f:X→S be a flat, proper morphism of finite presentation. Let F be an OX-module of finite presentation, flat over S. For fixed i∈Z consider the function βi:S→{0,1,2,…},s⟼dim_κ(s) H^i(Xs,Fs)
Then we have
  - formation of βi commutes with arbitrary base change,
  - the functions βi are upper semi-continuous, and
  - the level sets of βi are locally constructible in S
  - s⟼χ(Xs,Fs) is locally constant on S and formation of this function commutes with base change.

Proof. By cohomology and base change (more precisely by Lemma 35.27.4) the object K=Rf∗F is a perfect object of the derived category of S whose formation commutes with arbitrary base change. In particular we have H^i(Xs,Fs)=H^i(K⊗^L_OS κ(s)). cf [Schemes#Cohomologie]
Thus the lemma follows from Lemma 36.28.1:

* https://stacks.math.columbia.edu/tag/0BDI
$ 36.28 Perfect complexes

Lemma 36.28.1. Let X be a scheme. Let E∈D(OX) be pseudo-coherent (for example perfect). For any i∈Z consider the function
β_i:X⟶{0,1,2,…}, x ⟼ dim_κ(x) H^i(E⊗^L_OX κ(x))
Then we have
  - formation of βi commutes with arbitrary base change,
  - the functions βi are upper semi-continuous, and
  - the level sets of βi are locally constructible in X.

Lemma 36.28.2. Let X be a scheme. Let E∈D(OX) be perfect. The function
  χ_E:X⟶Z, x⟼∑ (−1)^i dim_κ(x) H^i(E⊗^L_OX κ(x))
is locally constant on X.

* See https://amathew.wordpress.com/2011/01/10/the-semicontinuity-theorem/
for a simpler proof (in less generality)
et http://math.uchicago.edu/~amathew/semicontinuity.pdf

Theorem 2.9 Let Y be  a  reduced  noetherian  scheme, f:X→Y a  proper  morphism,  and F a coherent sheaf on X flat over Y.  TFAE:1.  The function y→dim H^p(Xy,Fy) is locally constant. 2. R^pf_∗(F) is locally free on Y and the map R^pf_∗(F)⊗k(y)→H^p(Xy,Fy) is an isomorphism for y∈Y.
cf [Schemes#Cohomologie] pour plus de détails

Composantes connexes des fibres
-------------------------------

* Résumé
Si n_X/Y = nombres de composantes géom connexes (resp. de composantes géom irréd), et nn_X/Y la version non géom. Alors, si f de type fini
- pour tout y, n_X/Y est constant dans un ouvert V de *ybar*
  et sur V nn_X/Y >= nn_X/Y(y)
- Si f flat proper morphism of finite presentation,
  ou si f:X→Y separated locally quasi-finite universally open 
  (par exemple f:X->Y loc. quasi-finite et Y unibranch loc. noeth),
  n_X/Y est semi-continu inférieurement
- Si f flat proper morphism of finite presentation et les fibres sont géom
  réduites, n_X/Y est loc. constante.

* https://stacks.math.columbia.edu/tag/055C
$ 36.26 Connected components of fibres

Lemma 36.26.3. Let f:X→Y be a morphism of schemes. Let
  n_X/Y:Y→{0,1,2,3,…,∞}
be the function which associates to y∈Y the number of connected components of (Xy)K where K is a separably closed extension of κ(y). This is well defined and if g:Y′→Y is a morphism then n_X′/Y′=n_X/Y∘g
ie n_X/Y=nombres de composantes connexes géométriques

Lemmes: si f: X->Y de type fini, alors
- pour tout y, il existe un ouvert V de ybar tel que n_X/Y|V est constant.
- en particulier, si y est un point générique de Y et f^{-1}(y) est géom
  connexe, alors il existe un ouvert V de Y tel que les fibres sont géoms
  connexes
- si y est un point générique de Y, et f^{-1}(y) a m composantes connexes,
  alors il existe un ouvert V de Y tel que les fibres ont >=m composantes
  connexes.
- si f de prés finie, n_X/Y^{-1}(m) est loc. constructible dans Y

! Note: tous ces résultats sont vrais si on remplace (géom) connexe par
(géom) irréductible: https://stacks.math.columbia.edu/tag/0553, $ 36.25 Irreducible components of fibres

* https://stacks.math.columbia.edu/tag/03GX
$ 37.48 Stein factorization

[cas des applications propres et plates]
Lemma 36.48.7. Let X→S be a flat proper morphism of finite presentation. Let n_X/S be the function on Y counting the numbers of geometric connected components of fibres of f introduced in Lemma 36.26.3. Then n_X/S is lower semi-continuous. 

Lemma 36.48.8. Let f:X→S be a morphism of schemes. Assume
  - f is proper, flat, and of finite presentation, and
  - the geometric fibres of f are reduced.
Then the function n_X/S:S→Z counting the numbers of geometric connected components of fibres of f is locally constant.

* https://stacks.math.columbia.edu/tag/0F30
$ 36.66 Universally open morphisms

Lemma 36.66.6. Let f:X→Y be a separated, locally quasi-finite, and universally open morphism of schemes. 
- If n_X/Y(y)≥d for some y∈Y and d≥0, then n_X/Y≥d in an open neighbourhood of y
  ie n_X/Y(y) est semi-continu inférieurement
[où n_X/Y(y)=nombre de points géom dans les fibres = nombre de composantes
géoms connexes = nombre de composantes géom irréd vu que f est loc.
quasi-finie. De plus si X est qc, n_X/Y atteint un max d<∞]
- Si n_X/Y atteint un maximum d<∞, alors Y_d=n_X/Y^{-1}(d) est ouvert dans Y et f^−1(Y_d)→Y_d est fini.

Exemples
========

0) Penser à un blowup: la dimension jump au point du blowup

1) f: E->P^1 où E est une courbe elliptique
Morphisme fini de degré 2, donc plat.
Lisse en dehors des points de Weierstrass.
La fibre générique est de degré 2 (donné par un point de degré 2 qui géom devient deux points distincts), la fibre d'un point a un point double aux points de Weierstrass, soit deux points distincts, soit un point de degré 2 (qui donne deux points géométriques).

2) https://mathoverflow.net/questions/193/when-is-fiber-dimension-upper-semi-continuous

Our map is a composition X⊂A3→A3→Y⊂A4. We'll call the two A3's A and B respectively. X is the quasi-affine variety A∖{(0,∗,0)}. We map A→B by (x,y,z)↦(x,xy,z). We map the B to A4 by (p,q,r)↦(p(p−1),p2(p−1),q,r). Y is the affine variety {(a,b,c,d):a3=b(b−a)}. In other words, Y is the product of a nodal cubic with A2 . To see surjectivity, note that X hits every point of B where p is nonzero. The points of B where p≠0 map to the points of Y where (a,b)≠(0,0). The points (0,0,c,d) in Y are the images of (1,c,d)∈B, which are in turn the images of (1,c,d) in X . Now, let's look at dimf−1(0,0,0,r) . When r≠0, this is the union of (1,0,r) and (0,∗,r), so one dimensional. When r=0, the line (0,∗,0) is deleted, so the preimage is only a point.

- Let Y=k[x,y,z] and let Y′=k[x,y,z,w]/w2−z. Then let W be the blow-up of Y′ along x=0,w=1. Finally let X=W∖{x=0,y=0,w=1}. Then X and Y are regular varieties and the morphism X→Y has projective non-empty fibers. The inverse image of x=0,z=1 is the disjoint union of A1 (w=−1) and (A1∖{y=0})×P1. The fiber dimension is 0 outside {x=0,z=1} and 1 over {x=0,z=1} except at the point {x=0,y=0,z=1} where it is 0 again.

3) Exemples p.114 Dieudonné
