#!/usr/bin/zsh

PKGBUILD=$HOME/opt/arch/pkgs/pkgbuild

build() {
	pkg=$1
	dir=$(cut -b 1,2 <<< $pkg)
	mode=$3
	[[ -z $mode ]] && mode="--asexplicit"
	mkdir "$PKGBUILD/$pkg"
	cd "$PKGBUILD/$pkg"
	wget "https://aur.archlinux.org/packages/$dir/$pkg/PKGBUILD"
	makepkg
	cd "$PKGBUILD/../dest/"
	LIST=($pkg*)
	echo sudo pacman -U $mode $LIST[-1]
	sudo pacman --needed -U $mode $LIST[-1]
}

build "$@"
