#!/usr/bin/env ruby
#
# list optional dependencies of installed packages
#

class String
  def readlist
    return open("| #{self}").read.split("\n")
  end
end
allpackages="pacman -Qq".readlist

allpackages.each do |pkg|
	info=`pacman -Qi "#{pkg}"`
	opts=""
	info.lines do |l|
		if l =~ /Optional Deps/ ... l=~ /Required By/
			next if l =~ /Required By/
			l.sub!(/^(Optional Deps\s*:)?\s*/,'')
			opts +="- #{l}" unless l =~ /\[installed\]|None/
		end
	end
	print pkg+":\n"+opts unless opts.empty?
end
