#!/bin/sh

[ -z "$_INITVARS" ] && . "$HOME/.initvars"
mylog "session" ".fvwm/startup: $1"

case "$1" in 
"init" ) 
 exec $HOME/.fvwm/fenetre custom &
 ;; 
"initsession" ) 
 exec $HOME/.fvwm/fenetre custom &
 ;; 
esac 
