#!/bin/sh

setdefault() {
	DEVICE="$1"
	ponymix -d "$1" set-default
}

case "$MYHOSTNAME" in
	Feanor) 
		case "$1" in
			pci ) setdefault "alsa_output.pci-0000_00_1b.0.analog-surround-51" ;;
			headset ) 
				setdefault "alsa_output.pci-0000_00_1b.0.analog-surround-71"
				#setdefault "alsa_output.pci-0000_00_1b.0.analog-stereo"
				;;
			hdmi ) setdefault "alsa_output.pci-0000_00_1b.0.hdmi-stereo" ;;
			usb ) 
				setdefault "alsa_output.usb-DAC_FOR_USB_FOCAL_XS-00-XS.analog-stereo"
				#setdefault "alsa_output.usb-DAC_FOR_USB_FOCAL_XS-00-XS.iec958-stereo"
				;;
			*) 
				setdefault "alsa_output.usb-DAC_FOR_USB_FOCAL_XS-00-XS.analog-stereo"
				#setdefault "alsa_output.usb-DAC_FOR_USB_FOCAL_XS-00-XS.iec958-stereo"
				;;
		esac ;;
	Durin)
		#0: auto (hdmi si possible), 1: analog, 2: hdmi
		~/mine/script/raspberry audio "$@" ;;
esac
