#!/bin/sh

process() {
    systemctl "$@"
    exec dm-tool lock
}

case "$1" in
  logout ) exec xfce4-session-logout --logout ;;
  dialog ) exec xfce4-session-logout ;;
  lock ) exec dm-tool lock ;;
  * ) process "$@" ;;
esac
