#!/bin/sh

process() {
    #[ -e /usr/lib/seahorse/seahorse-ssh-askpass ] && export SUDO_ASKPASS="/usr/lib/seahorse/seahorse-ssh-askpass";
    #sudo -A cat /dev/null
    systemctl "$1" &
    exec dm-tool lock
}

case "$1" in
  logout ) exec xfce4-session-logout --logout ;;
  dialog ) exec xfce4-session-logout ;;
  lock ) exec dm-tool lock ;;
  * ) process "$1" ;;
esac
 
#exec gnome-session-save --gui

