#!/bin/zsh

HIGHLIGHT=1
CAT=
WORDS=
UNISON=
while true;
do
  case "$1" in
    -- ) break ;;
    -H ) shift; HIGHLIGHT= ;;
    -c ) shift; CAT=1 ;;
    --unison ) shift; UNISON=1 ;;
    -w ) shift; WORDS="--word-diff"; HIGHLIGHT= ;;
    -cH ) shift; HIGHLIGHT= CAT=1 ;;
    *) break;;
  esac
done

if [[ -n $UNISON ]]; then
  #for unison we want to go right to left
  #update: this is more convenient to go from left to right
  exec git diff --no-index $1 $2
fi

[[ -z $PAGER ]] && PAGER=less
HI="$HOME/mine/script/git/contrib/diff-highlight"

if [[ -z $CAT ]]; then
  if [[ -n $HIGHLIGHT ]]; then
    GIT_PAGER="$HI|$PAGER" exec git -c "color.ui=always" diff --no-index "$@"
  else
     exec git --paginate diff $WORDS --no-index "$@"
  fi
else
  if [[ -n $HIGHLIGHT ]]; then
    GIT_PAGER="$HI" exec git diff --no-index "$@"
  else
     exec git --no-pager diff $WORDS --no-index "$@"
  fi
fi
