#!/bin/zsh

MODE=highlight
CAT=
DIFFARGS=(-B "--color=always")
HIARGS=()
while true;
do
	case "$1" in
		-- ) break ;;
		--raw ) shift; MODE=raw ;;
		--unison ) shift; MODE=unison ;;
		-w ) shift; DIFFARGS+="--word-diff" ;;
		-c ) shift; CAT=t ;;
		*) break;;
	esac
done

HI="$HOME/script/git/diff-fancy.rb"
[[ -f $HI ]] || MODE="raw"
[[ -n $CAT ]] && HIARGS+="--no-pager"

case $MODE in
	raw )
		DIFFARGS+=("--color=auto")
		exec git diff --no-index $DIFFARGS $@ ;;
	unison )
		#for unison we want to go from left to right
		HIARGS+="--raw"
		DIFFARGS+=("--color=never")
		exec git diff --no-index $DIFFARGS $1 $2 | $HI $HIARGS ;;
	* ) exec git diff --no-index $DIFFARGS "$@" | $HI $HIARGS ;;
esac

