#!/bin/sh

FILE="/tmp/kramdown-tmp"
cat << EOF > "$FILE"
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
EOF
kramdown "$@" >> "$FILE"
cat << EOF >> "$FILE"
</body>
</html>
EOF
firefox "$FILE"
