#!/bin/zsh
renderer="pdflatex"
synctex=
aux=

while true;
do
  case "$1" in
    -- ) break ;;
    -bib ) shift; bibtex="true" ;;
    -lua ) shift; renderer='lualatex' ;;
    -xetex ) shift; renderer='xetex' ;;
    -synctex ) shift; synctex='true' ;;
    -aux ) shift; aux='true' ;; #for latex suite, but i have a patch that works directly
    #-bib8 ) shift; bib8='true' ;;
    *) break;;
  esac
done

#ARGS=()
#[ -n "$bib8" ] && ARGS=($ARGS -bibtex="bibtex8 --wolfgang %O %S")

latexcmd="$renderer -file-line-error -output-directory out"
[[ -n $synctex ]] && latexcmd="$latexcmd  -synctex=1"
[[ -n $aux ]] && latexcmd="$latexcmd; ln -s out/*.aux ."

echo $latexcmd "$@"
mkdir -p out
if [[ -z $bibtex ]]; then
  eval "$latexcmd $@" && cp out/*.pdf .
else
  eval "$latexcmd $@"
  [[ -n $bibtex ]] && bibtex out/${1%.tex}
  eval "$latexcmd $@" && cp out/*.pdf .
fi
