#!/bin/zsh

case $MYHOSTTYPE in
	imb)
		PDFVIEWER=evince texdoc "$@"
		;;
	*)
		FILE=$1
		BASE=$(basename $FILE)
		BASEF=${BASE%.pdf}.pdf
		DOCDIR="/var/tmp/latex"
		mkdir -p $DOCDIR && cd $DOCDIR
		if [[ -e $BASEF ]]; then
			evince $BASEF
		else
			if [[ $BASE == $FILE ]]; then
				#intuites the directory
				wget "ftp://tug.org/texlive/Contents/live/texmf-dist/doc/latex/$FILE/$FILE.pdf" && evince "$FILE.pdf"
			else
				wget "ftp://tug.org/texlive/Contents/live/texmf-dist/doc/$FILE" && evince $BASEF
			fi
		fi
		;;
esac
