#!/bin/sh
# total - sum up numbers in a column
# From: http://chneukirchen.org/dotfiles/bin/total

expr "$1" : -F >/dev/null && F=$1 && shift
#-F expr define the separator
exec awk $F -v f=${1:-1} '{s+=$f} END{print s}' "$@"
