#!/bin/zsh

MOUNTMODE=udisk
MODE=
#UUID=20d96426-1f4d-4fec-8aa9-287e0142051f
LABEL=usbinria
MOUNTDISK=$(findfs "LABEL=$LABEL")
MOUNTTARGET=/run/media/dams/$LABEL
DIRHOME="$MOUNTTARGET/home/dams"

#options: MOUNTMODE=sudo or MOUNTMODE=udisk
while true;
do
	case "$1" in
		-- ) break ;;
		-m|--mode ) shift; MODE=$1; shift ;;
		-s|--sudo ) shift; MOUNTMODE=sudo;;
		-u|--udisk ) shift; MOUNTMODE=udisk;;
		--mount ) shift; MODE=mount;;
		--umount|--unmount ) shift; MODE=umount;;
		--sync ) shift; MODE=sync;;
		*) break;;
	esac
done

MOUNTOPTS="compress=lzo"

do_sync() {
	if [[ -d $DIRHOME ]]; then
		USBGIT="$DIRHOME/var/backups/gitbackup"
		mkdir -p $USBGIT
		git init --bare $USBGIT
		echo "$ git push --all $USBGIT"
		cd ~/var/backups/gitbackup
		git push --all $USBGIT
		cd
		echo "$ unison.rb $@ usb_backup"
		unison.rb --push "$@" usb_backup
		echo "$ sync"
		sync
	else
		echo "# $DIRHOME is not available"
	fi
}

case $MODE in
	mount) do_mount ;;
	umount) do_umount ;;
	sync) do_sync ;;
	*)
		do_mount
		do_sync
		[[ -n $DID_MOUNT ]] && do_umount
		;;
esac
