#!/bin/zsh

MELD=
while true;
do
  case "$1" in
    -- ) break ;;
    -m ) shift; MELD=1 ;;
    *) break;;
  esac
done

DIRnew="/var/tmp/etc-diff.pacnew"
DIR="/var/tmp/etc-diff"
rm -rf "$DIRnew"
rm -rf "$DIR"
mkdir "$DIRnew"
mkdir "$DIR"

for pathnew in /etc/**/*.pacnew; do
  thepath=${pathnew%.pacnew}
  #file=$(basename "$thepath")
  #grmbl i need to desactivate the new sysctl preventing some hardlinks...
  mkdir -p "$DIRnew/$(dirname $thepath)"
  mkdir -p "$DIR/$(dirname $thepath)"
  sudo ln "$pathnew" "$DIRnew/$thepath"
  sudo ln "$thepath" "$DIR/$thepath"
done

if [ -z "$MELD" ]; then
	#we miss non readable files without sudo
  sudo gitdiff $DIR $DIRnew
else
  DBUS_SESSION_BUS_ADDRESS= sudo meld "$DIRnew" "$DIR"
fi
