#!/bin/zsh

#we want to creat slash as a subvolume to facilitate snapshots
TMPTARGET=$TARGET_DIR
mkdir -p $TMPTARGET
DSLASH=$(findfs LABEL=slash || ${DISK}1)
mount $DSLASH $TARGET_DIR

sudo btrfs subvolume create $TMPTARGET/slash
sudo btrfs subvolume create $TMPTARGET/home
sudo btrfs subvolume create $TMPTARGET/data

umount $TMPTARGET

mount -o subvol=/slash $DSLASH $TARGET_DIR &&
mount $DSLASH "$TARGET_DIR/mnt" &&
mkdir -p $TARGET_DIR/boot $TARGET_DIR/home $TARGET_DIR/data &&
mount -o subvol=/home $DSLASH $TARGET_DIR/home &&
mount -o subvol=/data $DSLASH $TARGET_DIR/data &&
[[ $DSLASH != ${DISK}1 ]] && mount ${DISK}1 $TARGET_DIR/boot
