#!/bin/zsh

MELD=
ACTION=cp
while true;
do
  case "$1" in
    -- ) break ;;
    -m ) shift; MELD=1 ;;
    -ln ) shift; ACTION="ln" ;;
    *) break;;
  esac
done

DEFAULT="$HOME/mine/syst/@comps/$MYHOSTNAME/slash"
DIR=${1-$DEFAULT}
ODIR=${2-/}
cd $DIR

OUTDIR="/var/tmp/slash-snapshot"
rm -rf "$OUTDIR"
mkdir "$OUTDIR"

(
cd $DIR
for file in **/{*,.*}; do
  [[ -d $file ]] && mkdir -p "$OUTDIR/$file";
  [[ -f $file ]] && sudo $ACTION "$ODIR/$file" "$OUTDIR/$file"
done
)

#sudo chmod 644 "$OUTDIR/etc/sudoers"

if [[ -z $MELD ]]; then
  gitdiff $OUTDIR .
else
  meld "." "$OUTDIR"
fi
