#!/bin/sh
case "$MYHOSTTYPE" in
## mpd
  perso ) cat <<'EOS'
AddToFunc SetBindings
+ I Key c A C4 Exec exec mpc-notify pause
+ I Key v A C4 Exec exec mpc-notify play
+ I Key b A C4 Exec exec mpc-notify prev
+ I Key n A C4 Exec exec mpc-notify next
+ I Key x A C4 Exec exec mpc seek +10
+ I Key w A C4 Exec exec mpc seek -10

+ I Key XF86AudioLowerVolume A N Exec exec volume decrease 5
+ I Key XF86AudioRaiseVolume A N Exec exec volume increase 5
+ I Key XF86AudioMute A N Exec exec volume toggle
+ I Key XF86AudioPlay A N Exec exec mpc-notify toggle
+ I Key XF86AudioNext A N Exec exec mpc-notify next
+ I Key XF86AudioPrev A N Exec exec mpc-notify prev

EwmhBaseStruts 0 0 30 0
EOS
;;
esac

case "$MYHOSTNAME" in
  Gondolin ) cat <<'EOS'
AddToFunc SetBindings
+ I Key F9 A M Menu MainStyleMenu Root c c
+ I Key F10 A M Menu SaveSessionMenu Root c c
+ I Key F11 A M Menu RestartMenu Root c c
+ I Key F12 A M Menu QuitMenu Root c c
 
+ I Key 0 A SM Exec $HOME/.fvwm/fenetres/fenetre_screen
+ I Key 9 A SM Exec $HOME/.fvwm/fenetres/fenetre2_screen
+ I Key 8 A SM Exec $HOME/.fvwm/fenetres/fenetre3_screen
+ I Key 1 A SM Exec $HOME/.fvwm/fenetres/fenetre_ul_screen
+ I Key 2 A SM Exec $HOME/.fvwm/fenetres/fenetre_dl_screen
+ I Key 3 A SM Exec $HOME/.fvwm/fenetres/fenetre_ur_screen
+ I Key 4 A SM Exec $HOME/.fvwm/fenetres/fenetre_dr_screen
 
+ I Key Right A M GotoPage +1p +0p
+ I Key Left  A M GotoPage -1p +0p
+ I Key Up    A M GotoPage +0p -1p
+ I Key Down  A M GotoPage +0p +1p
+ I Key Next A M ChangeDesktop +1 0 0 3
+ I Key Prior A M ChangeDesktop -1 0 0 3
+ I Key Home A M GotoDeskAndPage 0 1 1
+ I Key End A M GotoPage 1 1
+ I Key Return A M GotoDeskAndPage prev

+ I Key Tab   A M Next (CurrentPage, !Shaded) Function WarpFocus
+ I Key Tab   A MC Next (CurrentPage) Function WarpFocus
+ I Key Tab   A MS Next (CurrentPage, Shaded) Function WarpFocus

+ I Key Left A SM Direction West (CurrentPage) Function Warp
+ I Key Right A SM Direction East (CurrentPage) Function Warp
+ I Key Up A SM Direction North (CurrentPage) Function Warp
+ I Key Down A SM Direction South (CurrentPage) Function Warp

+ I Key Prior A SM Prev (CurrentPage) Function WarpFocus
+ I Key Next A SM Next (CurrentPage) Function WarpFocus
+ I Key Home A SM Prev (CurrentDesk) Function WarpFocus
+ I Key End A SM Next (CurrentDesk) Function WarpFocus

+ I Key F2 A M  WindowList Root c c \
            IconifiedAtEnd,NoGeometryWithInfo 
+ I Key A A MC WindowList Root c c \
            CurrentDesk,IconifiedAtEnd,\
            NoGeometryWithInfo,NoDeskNum 
+ I Key A A MS WindowList Root c c \
            IconifiedAtEnd,\
            NoGeometryWithInfo,NoDeskNum 
+ I Key Q A MC WindowList (CurrentGlobalPage) Root c c \
            NoIcons, \
            NoGeometryWithInfo,NoDeskNum 
+ I Key Q A MS WindowList (CurrentGlobalPage) Root c c \
            OnlyIcons, \
            NoGeometryWithInfo,NoDeskNum
+ I Key S A MC WindowList (CurrentDesk, !Iconic) Root c c \
            NoGeometryWithInfo,NoDeskNum 
+ I Key S A MS WindowList (CurrentDesk, Iconic) Root c c \
            NoGeometryWithInfo,NoDeskNum
+ I Key D A MC WindowList Root c c \
            NoIcons, \
            NoGeometryWithInfo,NoDeskNum
+ I Key D A MS WindowList (Iconic) Root c c \
            NoGeometryWithInfo,NoDeskNum
 
+ I Key E A MC Menu QuickStart Root c c 
+ I Key Z A MC Menu Programmes Root c c
+ I Key Z A MS Menu Programmes Root +0 +100
+ I Key W A MC Menu Programmes Root c c
+ I Key W A MS Menu Programmes Root +0 +100
+ I Key O A MC Scroll
+ I Key O A MS Scroll reverse
 
+ I Key R A MC ToggleWindow "FVWMmulticommand" "Exec exec xterm -name FVWMmulticommand -title Console -e screen"
+ I Key R A MS ToggleWindowCurrentPage "FVWMmulticommandCP" "Exec exec xterm -name FVWMmulticommandCP -title ConsoleCurrentPage -e screen"
+ I Key P A MC Menu FvwmFuncMenu Root c c
+ I Key P A MS Function ToggleWindow "FvwmPager" "Module FvwmPager 0 3"
+ I Key I A MC ToggleWindow "Conky" "Exec exec conky"
+ I Key I A MS ToggleWindowUpDown "Conky" 2 6
 
+ I Key KP_Home A MC      WindowId root 1 WarpToWindow 0 0
+ I Key KP_Up A MC        WindowId root 1 WarpToWindow 50 0
+ I Key KP_Page_Up A MC   WindowId root 1 WarpToWindow 100 0
+ I Key KP_Left A MC      WindowId root 1 WarpToWindow 0 50
+ I Key KP_Begin A MC     WindowId root 1 WarpToWindow 50 50
+ I Key KP_Right A MC     WindowId root 1 WarpToWindow 100 50
+ I Key KP_End A MC       WindowId root 1 WarpToWindow 0 100
+ I Key KP_Down A MC      WindowId root 1 WarpToWindow 50 100
+ I Key KP_Page_Down A MC WindowId root 1 WarpToWindow 100 100
 
+ I Key Space WTFSI M Raise
+ I Key BackSpace  WTFSI M Lower
 
# i want to quit X with that
#+ I Key BackSpace WTFSI CM WindowShade Toggle
+ I Key Return WTFSI CM Function Restore
+ I Key Space WTFSI CM Menu StickMenu Root c c

+ I Key Insert WTFSI M Resize Direction NW warptoborder
+ I Key Delete WTFSI M Resize Direction SE warptoborder
+ I Key Insert WTFSI SM ResizeMaximize Direction NW warptoborder
+ I Key Delete WTFSI SM ResizeMaximize Direction SE warptoborder
+ I Key Insert WTFSI CM Menu MoveMenu Root c c
+ I Key Delete WTFSI CM Menu ResizeMenu Root c c

+ I Key Right WTFSI CM MoveAndFollow +1p +0p
+ I Key Left  WTFSI CM MoveAndFollow -1p +0p
+ I Key Up    WTFSI CM MoveAndFollow +0p -1p
+ I Key Down  WTFSI CM MoveAndFollow +0p +1p
+ I Key Next WTFSI CM MoveToDeskAndFollow +1 0 0 3
+ I Key Prior WTFSI CM MoveToDeskAndFollow -1 0 0 3
+ I Key Home WTFSI CM MoveAndFollow 1 1
+ I Key End WTFSI CM Function MoveToOrig

+ I Key F1 A M  Menu MainWindowMenu 
+ I Key F3 WTFSI M Function BMenu
+ I Key F4 WTFSI M Delete
+ I Key F5 WTFSI M Iconify toggle
+ I Key F6 WTFSI M Maximize 100 100
+ I Key F6 WTFSI SM Maximize true 0 100

+ I Key h WTFSI SM Maximize true growleft 0
+ I Key j WTFSI SM Maximize true 0 growdown
+ I Key k WTFSI SM Maximize true 0 growup
+ I Key l WTFSI SM Maximize true growright 0
+ I Key m WTFSI SM Maximize true 100 100
+ I Key g WTFSI SM Maximize false
+ I Key f WTFSI SM Function BMaxOff

+ I Key h WTFSI CM Move +0 w
+ I Key j WTFSI CM Move w -0
+ I Key k WTFSI SCM Move w +28p
+ I Key k WTFSI CM Move w +0
+ I Key l WTFSI CM Move -0 w
+ I Key g WTFSI MC Move 50-50w 50-50w
+ I Key semicolon WTFSI MC Move 
+ I Key m WTFSI MC Move
+ I Key f WTFSI MC PlaceAgain

+ I Key KP_Home WTFSI M WarpToWindow 0 0
+ I Key KP_Up WTFSI M WarpToWindow 50 0
+ I Key KP_Page_Up WTFSI M WarpToWindow 100 0
+ I Key KP_Left WTFSI M WarpToWindow 0 50
+ I Key KP_Begin WTFSI M WarpToWindow 50 50
+ I Key KP_Right WTFSI M WarpToWindow 100 50
+ I Key KP_End WTFSI M WarpToWindow 0 100
+ I Key KP_Down WTFSI M WarpToWindow 50 100
+ I Key KP_Page_Down WTFSI M WarpToWindow 100 100

+ I Key U A CM WindowStyle FPEnterToFocus
+ I Key I A CM WindowStyle !FPEnterToFocus
+ I Key T A CM WindowStyle Title
+ I Key Y A CM WindowStyle !Title

Mouse 1  A   MC Scroll reverse
Mouse 1  A   MS Scroll
Mouse 3  A   MS \
  WindowList  \
  IconifiedAtEnd,NoGeometryWithInfo,NoDeskNum 
Mouse 2  A   MC Module FvwmPager -transient 0 3
Mouse 3  R   M \
  WindowList \
  IconifiedAtEnd,NoGeometryWithInfo,NoDeskNum 
Mouse 1 I M IconFunc
Mouse 4 A M Previous (CurrentPage) Function Warp
Mouse 5 A M Next (CurrentPage) Function Warp
Mouse 4 A MS GotoDesk -1 0 0 3
Mouse 5 A MS GotoDesk +1 0 0 3
Mouse 4 A MC Scroll -100000 0
Mouse 5 A MC Scroll 100000 0
Mouse 1  FSWT M Function Raise-and-move
Mouse 2  WTFS M Move
Mouse 3  WTFS M Function LowerAndResize
EOS
;;
esac

