#!/bin/zsh

#INITPKGS is defined in ZZvars

case $BOOTLOADER in
	grub) INITPKGS+=grub ;;
	syslinux ) INITPKGS+=syslinux ;;
	gummiboot) INITPKGS+=(efibootmgr gummiboot) ;;
esac

pacstrap $TARGET_DIR $INITPKGS
