#!/bin/zsh

case $BOOTLOADER in
	grub) #bios
		grub-install --directory=/usr/lib/grub/i386-pc --target=i386-pc --boot-directory=/boot --recheck $DISK ;;
		#modifier /etc/grub.d/40_custom pour rajouter windows
		#editer ~etc/default/grub
		#sudo grub-mkconfig -o /boot/grub/grub.cfg
	syslinux ) #bios
		#no need for -a, I already marked the partition bootable (and -a only
		#work for mbr partitions anyway)
		syslinux-install_update -i -m;;
	gummiboot) #efi
		gummiboot install
		#install shellx64_v1.efi and shellx64_v2.efi:
		cp -a $DIR/EFI /boot/
		;;
esac

if [[ -n $BOOTBACKUP ]]; then
	cd /boot
	case $BOOTLOADER in
		grub)
			sudo cp vmlinuz-linux vmlinuz-linuw00
			sudo cp initramfs-linux.img initramfs-linuw00.img
			sudo cp initramfs-linux-fallback.img initramfs-linuw00-fallback.img
			;;
		syslinux|gummiboot)
			sudo mkdir -p linux-init
			sudo cp vmlinuz-linux initramfs-linux.img initramfs-linux-fallback.img linux-init/
			;;
	esac
fi
