#!/bin/zsh

#Set locale preferences in /etc/locale.conf.
for LANGUAGE in $LANGS; do
  sed -i "s/#${LANGUAGE}/${LANGUAGE}/" /etc/locale.gen
done
locale-gen

systemd-machine-id-setup

#somewhat redondant with 21config, but this does not need a running systemd
systemd-firstboot --root=/ --locale=$LOCALE_LANG --timezone=$TIMEZONE --hostname="$NEWHOSTNAME" --setup-machine-id
#locale: /etc/locale.conf
#timezone: /etc/localtime

#It's better to run in the chroot because here we have the last version of
#systemd. But we can't invoke --setup-machine-id right now when root=/, see bug
#https://bugs.archlinux.org/task/41711
#
#So meanwhile I first call systemd-machine-id-setup
#to generate the machine id.
