#!/bin/zsh
#TODO: use preset instead

sudo systemctl enable systemd-timesyncd sshd.socket
sudo systemctl enable systemd-networkd systemd-resolved
#sudo ln -snf /run/systemd/resolv/resolv.conf /etc/resolv.conf
#unfortunately this does not work under arch-chroot because resolv.conf is bind mounted

#sudo systemctl enable systemd-readahead-collect systemd-readahead-replay

#internet: netctl
# sudo systemctl enable netctl-ifplugd@eth0.service
# sudo systemctl enable netctl-auto@wlan0.service
# sudo cp ~dams/config/syst/netctl/wlan0-LapinouBlanc /etc/netctl
# sudo netctl enable wlan0-LapinouBlanc

#networkd:
# sudo cp ~system-generate/files/systemd/network/* /etc/systemd/network/
# sudo cp ~system-generate/files/wpa_supplicant/* /etc/wpa_supplicant
# cd /etc && sudo ln -snf /run/systemd/resolv/resolv.conf /etc/resolv.conf
#Attention, pour nommer les interfaces eth0 et wlan0, il faut faire une
#règle udev qui matche sur le dhcp, cf:
# ~system-generate/files/udev/rules.d/80-net-setup-link.rules

#lightdm
# sudo systemctl enable lightdm.service
