#!/bin/zsh
. "$(dirname $0)/_install_helpers"

url="gh:fvwmorg/$(basename $0)"
# version="2.6.8"
export LAST_TAG="git tag | egrep '^([[:digit:]]+.?)*$' | sort --version-sort | tail -n1"

build_helper $@
build_git -- --with-stroke-library $args
