#!/bin/zsh
. "$(dirname $0)/_install_helpers"

typeset -A versions
versions[libgpg-error]="1.36"
versions[libgcrypt]="1.8.4"
versions[libksba]="1.3.5"
versions[libassuan]="2.5.3"
versions[npth]="1.6"
versions[gnupg]="2.2.17"

for prog in ${(@k)versions}; do
  progv="$prog-$versions[$prog]"
  echo "============= $progv ================"
  #read
  archive="$progv.tar.bz2"
  do_build $prog $progv $archive https://www.gnupg.org/ftp/gcrypt/$prog/$archive
done

[[ -e $OPT/bin/gpg2 ]] && ln -s gpg2 $OPT/bin/gpg
[[ -e /usr/bin/pinentry ]] && ln -s /usr/bin/pinentry $OPT/packages/gnupg/bin/
