#!/bin/zsh
. "$(dirname $0)/_install_helpers"

url=ocaml
# version="4.08.0"
export LAST_TAG="git tag | egrep '^([[:digit:]]+.?)*$' | sort --version-sort | tail -n1"
build_helper $@

CUSTOM_COMPILE='
./configure --prefix $prefix &&
make world &&
make opt &&
make install'

build_git
