#!/bin/zsh
. "$(dirname $0)/_install_helpers"

export LAST_TAG="git tag | grep 'stable' | sort --version-sort | tail -n1"
# build_git -l "libevent" "release-2.1.11-stable"
build_git -l "libevent" "release-2.1.11-stable"

export LAST_TAG=
url=tmux
# version="2.9"
build_helper $@
build_git
